server:
  port: 8006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: diploma-service
          uri: lb://diploma-service
          predicates:
            - Path=/diploma/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: subject-service
          uri: lb://subject-service
          predicates:
          - Path=/subject/**
